# Generated by Django 6.0 on 2026-01-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_index',
            field=models.IntegerField(default=0),
        ),
    ]
